version: '3.8'

services:
  # Main benchmark service
  vid-bench:
    build: .
    container_name: vid-diffusion-benchmark
    volumes:
      - ./results:/app/results
      - ./models:/app/models
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - TORCH_HOME=/app/models/.torch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - vid-bench-network

  # Redis for caching and job queues
  redis:
    image: redis:7-alpine
    container_name: vid-bench-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - vid-bench-network

  # Streamlit dashboard
  dashboard:
    build: .
    container_name: vid-bench-dashboard
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
      - ./dashboard:/app/dashboard
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - vid-bench-network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: vid-bench-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - vid-bench-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: vid-bench-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - vid-bench-network

volumes:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  vid-bench-network:
    driver: bridge