# Alertmanager Configuration for Video Diffusion Benchmark Suite

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@vid-diffusion-bench.com'
  slack_api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    - match:
        service: vid-diffusion-bench
      receiver: 'benchmark-team'

receivers:
  - name: 'default'
    email_configs:
      - to: 'admin@vid-diffusion-bench.com'
        subject: '[VID-BENCH] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels:
          {{ range .Labels.SortedPairs }}  - {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        color: 'danger'
        send_resolved: true
    email_configs:
      - to: 'oncall@vid-diffusion-bench.com'
        subject: '[CRITICAL] VID-BENCH Alert'
        body: |
          CRITICAL ALERT TRIGGERED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          
          Labels:
          {{ range .Labels.SortedPairs }}  - {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  - name: 'benchmark-team'
    slack_configs:
      - channel: '#benchmark-alerts'
        title: 'Benchmark Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}
        color: 'warning'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '(HighBenchmarkFailureRate|SlowModelInference|QueueBacklog)'
    equal: ['service']