global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vid-diffusion-benchmark'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Vid Diffusion Benchmark metrics
  - job_name: 'vid-diffusion-benchmark'
    static_configs:
      - targets: ['vid-bench:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # GPU metrics
  - job_name: 'nvidia-dcgm-exporter'
    static_configs:
      - targets: ['nvidia-dcgm-exporter:9400']
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Docker metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093